import java.util.HashMap;

public class HelperLists {

    public HashMap<String, String> getDepartments() {
        HashMap<String, String> departments = new HashMap<String,String>();
        for (String[] q : departmentStrings) {
            departments.put(q[1], q[0]);
        }
        return departments;
    }

    public CourseAttribute getAttributeObject (String acronym) {

        CourseAttribute newAttribute = new CourseAttribute();
        newAttribute.acronym = acronym;
        for (String[] q : attributeStrings) {
            if(q[0].equals(acronym)) {
                newAttribute.name = q[1];
                return newAttribute;
            }
        }
        newAttribute.name = "";
        return newAttribute;
    }
    String [][] attributeStrings = new String[][] {
            {"BCOM", "GWSB-Communications Elective"},
            {"BCPD", "GWSB-Cult.&Political Diversity"},
            {"BFCO", "GWSB-Foreign Cultures Option"},
            {"BFLC", "GWSB-Foreign Lang. or Culture"},
            {"BHUM", "GWSB-Humanities Elective"},
            {"BINT", "GWSB-International Bus. Elec."},
            {"BMRE", "GWSB-Moral Reasoning Elective"},
            {"CAA", "CCAS: Arts"},
            {"CAF1", "CCAS-AMST-Cultural Politics"},
            {"CAF2", "CCAS-AMST-Global Connections"},
            {"CAF3", "CCAS-AMST-Space, Place,Society"},
            {"CAF4", "CCAS-AMST-Power, Iden, Diff"},
            {"CAF5", "CCAS-AMST-Built Environment"},
            {"CAF6", "CCAS-AMST-Cultural Analysis"},
            {"CAH", "GenEd:Crit Analysis Humanities"},
            {"CAMS", "GenEd:Quantitative Reasoning"},
            {"CASS", "GenEd:Crit Analysis Social Sci"},
            {"CCCP", "CCAS-GCR: CPA"},
            {"CCFC", "CCAS - GCR: Foreign Cultures"},
            {"CCFL", "CCAS - GCR: Foreign Languages"},
            {"CCH", "CCAS - GCR: Humanities"},
            {"CCNS", "CCAS - GCR: Natural Sciences"},
            {"CCOM", "CCAS: Oral Communication"},
            {"CCPR", "CCAS - Professional"},
            {"CCQL", "CCAS - GCR: Q & L"},
            {"CCSB", "CCAS - GCR:Social & Behavioral"},
            {"CDEL", "CCAS - Dance Electives"},
            {"CDPP", "CCAS - Dramatic Lit.-Perf&Prod"},
            {"CDRA", "CCAS - Dramatic Lit - Drama"},
            {"CEDE", "SEAS-CE Design Elective"},
            {"CETE", "SEAS-CE Technical Elective"},
            {"CGCC", "CCAS:GlobalCrossCultural"},
            {"CGHG", "CCAS-GEOG - Human Geography"},
            {"CGPG", "CCAS-GEOG - Physical Geography"},
            {"CGRG", "CCAS-GEOG - Regional Geography"},
            {"CHIE", "CCAS - History European"},
            {"CHIU", "CCAS - History US"},
            {"CHIW", "CCAS - History World"},
            {"CHPS", "CCAS - History Pre-1750"},
            {"CLCE", "CCAS:Local/Civil Engage"},
            {"CSCI", "Gen Ed: Nat or Phys Sci"},
            {"CT01", "TSPPPA - Budget&Finance"},
            {"CT02", "TSPPPA - Education Policy"},
            {"CT03", "TSPPPA - Environmental Policy"},
            {"CT04", "TSPPPA - Fed Pol, Polit & Mgmt"},
            {"CT05", "TSPPPA - Health Policy"},
            {"CT06", "TSPPPA - Homeland Security"},
            {"CT07", "TSPPPA - International Dev Mgt"},
            {"CT08", "TSPPPA - International Dev Pol"},
            {"CT09", "TSPPPA - State&Local Govs"},
            {"CT10", "TSPPPA - National Security Pol"},
            {"CT11", "TSPPPA - Nonprofit Mgmt"},
            {"CT12", "TSPPPA - Policy Analys & Eval"},
            {"CT13", "TSPPPA - Program Eval & Analys"},
            {"CT14", "TSPPPA - Pub-Pri Pol Mgmt"},
            {"CT15", "TSPPPA - Regulatory Policy"},
            {"CT16", "TSPPPA - Social Policy"},
            {"CT17", "TSPPPA - Urban Policy"},
            {"CTDP", "CCAS - Theatre-Dram.Lit &Play"},
            {"CTDT", "CCAS - Theatre-Design & Tech"},
            {"CTEL", "CCAS - Theatre Electives"},
            {"CTRN", "CCAS-GPAC Transfer Courses"},
            {"CXCL", "Not Counted Certificate"},
            {"DGW1", "Degree Audit Attribute"},
            {"DGW2", "Degree Audit Attribute 2"},
            {"DNCE", "Dance"},
            {"EAED", "ESIA-Asian Studies-Econ & Devl"},
            {"EAHC", "ESIA-Asian Studies-Hist & Cult"},
            {"EAPG", "ESIA-Asian Studies-Psc/Geog"},
            {"ESCA", "ESIA-Creative Arts Courses"},
            {"ESCI", "ESIA-Science(2010)"},
            {"ESHA", "ESIA-Historical Analysis"},
            {"ESHC", "ESIA-Humanities Courses"},
            {"ESIP", "ESIA-International Politics"},
            {"ESRM", "ESIA-Research Methods"},
            {"HAAH", "HONR - Arts & Hum. HONR 2053"},
            {"HAH2", "HONR - Arts & Hum. HONR 2054"},
            {"HSAS", "HONR-Self & Society HONR 2047"},
            {"HSRD", "HONR-Sci Reasoning & Discovery"},
            {"HSS2", "HONR-Self & Society HONR 2048"},
            {"JDSR", "JD-LAW Skills Requirement"},
            {"JDWR", "JD-LAW Writing Requirement"},
            {"MPGC", "MBA Professional - Global"},
            {"MPSC", "MBA Prof - Sustainability"},
            {"MXCL", "Not Counted Masters Program"},
            {"NCAP", "Not Counted"},
            {"PCPA", "SPHHS-Creative/Performing Arts"},
            {"PHHC", "SPHHS-Humanities Courses"},
            {"SHUM", "Inactive Attribute Code"},
            {"SMTA", "Sust Minor: Green Leaf Track A"},
            {"SMTB", "Sust Minor: Green Leaf Track B"},
            {"SMTC", "Sust Minor: Green Leaf Track C"},
            {"SUST", "Sustainability Courses"},
            {"SVCL", "Service Learning Course"}
    };
    String [][] departmentStrings = new String[][] {
            {"Academy for Classical Acting", "ACA"},
            {"Accountancy", "ACCY"},
            {"Africana Studies", "AFST"},
            {"American Studies", "AMST"},
            {"Anatomy and Regenerative Biology", "ANAT"},
            {"Anthropology", "ANTH"},
            {"Applied Science", "APSC"},
            {"Arabic", "ARAB"},
            {"Art History", "AH"},
            {"Art Therapy", "ARTH"},
            {"Astronomy", "ASTR"},
            {"Biochemistry", "BIOC"},
            {"Biological Sciences", "BISC"},
            {"Biomedical Engineering", "BME"},
            {"Biomedical Sciences", "BMSC"},
            {"Biostatistics", "BIOS"},
            {"Business Administration", "BADM"},
            {"Chemistry", "CHEM"},
            {"Chinese", "CHIN"},
            {"Civil Engineering", "CE"},
            {"Classical Studies", "CLAS"},
            {"Clinical Management and Leadership", "CML"},
            {"Clinical Research Admin", "CRA"},
            {"College of Professional Studies", "CPS"},
            {"Columbian College", "CCAS"},
            {"Communication", "COMM"},
            {"Computer Science", "CSCI"},
            {"Corcoran Art and the Book", "CBK"},
            {"Corcoran Art Education", "CED"},
            {"Corcoran Art History", "CAH"},
            {"Corcoran Arts and Humanities", "CAS"},
            {"Corcoran Ceramics", "CCR"},
            {"Corcoran Continuing Education", "CCE"},
            {"Corcoran Decorative Arts and Design", "CDAD"},
            {"Corcoran Design", "CDE"},
            {"Corcoran Digital Media Design", "CDM"},
            {"Corcoran Exhibition Design", "CEX"},
            {"Corcoran Fine Art", "CFA"},
            {"Corcoran First Year Foundation", "CFN"},
            {"Corcoran Graphic Design", "CGD"},
            {"Corcoran Interior Design", "CID"},
            {"Corcoran Photography", "CPH"},
            {"Corcoran Photojournalism", "CPJ"},
            {"Corcoran Printmaking", "CPR"},
            {"Corcoran Sculpture", "CSL"},
            {"Counseling", "CNSL"},
            {"Curriculum and Pedagogy", "CPED"},
            {"Data Science", "DATS"},
            {"Decision Sciences", "DNSC"},
            {"East Asian Language and Literature", "EALL"},
            {"Economics", "ECON"},
            {"Educational Leadership", "EDUC"},
            {"Electrical and Computer Engring", "ECE"},
            {"Emergency Health Services", "EHS"},
            {"Engineering Management and Systems Engineering", "EMSE"},
            {"English", "ENGL"},
            {"English for Academic Purposes", "EAP"},
            {"Environmental Resource Policy", "ENRP"},
            {"Environmental Studies", "ENVR"},
            {"Epidemiology", "EPID"},
            {"Exercise and Nutrition Sciences", "EXNS"},
            {"Film Studies", "FILM"},
            {"Finance", "FINA"},
            {"Fine Arts", "FA"},
            {"Forensic Psychology", "FORP"},
            {"Forensic Sciences", "FORS"},
            {"French", "FREN"},
            {"Geography", "GEOG"},
            {"Geology", "GEOL"},
            {"Germanic Language and Literature", "GER"},
            {"Government Contracts", "GCON"},
            {"Greek", "GREK"},
            {"GWTeach", "GTCH"},
            {"Health Care Quality", "HCQ"},
            {"Health Care Science", "HCS"},
            {"Health Sciences Programs", "HSCI"},
            {"Health Services Management and Leadership", "HSML"},
            {"Health and Wellness", "HLWL"},
            {"Hebrew", "HEBR"},
            {"History", "HIST"},
            {"Hominid Paleobiology", "HOMP"},
            {"Honors", "HONR"},
            {"Human Development", "HDEV"},
            {"Human Organizational Learning", "HOL"},
            {"Human Services and Social Justice", "HSSJ"},
            {"Informatics", "INFR"},
            {"Information Systems Technology Management", "ISTM"},
            {"Integrative Medicine", "INTM"},
            {"Interior Architecture", "IA"},
            {"International Affairs", "IAFF"},
            {"International Business", "IBUS"},
            {"Italian", "ITAL"},
            {"Japanese", "JAPN"},
            {"Judaic Studies", "JSTD"},
            {"Korean", "KOR"},
            {"Latin", "LATN"},
            {"Law", "LAW"},
            {"Legislative Affairs", "LGAF"},
            {"Lifestyle, Sport, and Physical Activity", "LSPA"},
            {"Linguistics", "LING"},
            {"Management", "MGT"},
            {"Marketing", "MKTG"},
            {"Master of Business Administration", "MBAD"},
            {"Mathematics", "MATH"},
            {"Mechanical and Aerospace Engineering", "MAE"},
            {"Medical Laboratory Science", "MLS"},
            {"Microbiology, Immunology, and Tropical Medicine", "MICR"},
            {"Molecular Medicine", "MMED"},
            {"Museum Studies", "MSTD"},
            {"Music", "MUS"},
            {"Naval Science", "NSC"},
            {"Nursing", "NURS"},
            {"Organizational Sciences", "ORSC"},
            {"Patent Practice", "PATN"},
            {"Peace Studies", "PSTD"},
            {"Persian", "PERS"},
            {"Pharmacogenomics", "PHRG"},
            {"Pharmacology", "PHAR"},
            {"Philosophy", "PHIL"},
            {"Physical Therapy", "PT"},
            {"Physician Assistant", "PA"},
            {"Physics", "PHYS"},
            {"Physiology", "PHYL"},
            {"Political Management", "PMGT"},
            {"Political Psychology", "PPSY"},
            {"Political Science", "PSC"},
            {"Portuguese", "PORT"},
            {"Professional Studies Advocacy Global Environment", "PSAD"},
            {"Professional Studies Cybersecurity Strategy and Information Management", "PSCS"},
            {"Professional Studies Healthcare Corporate Complaince", "PSHC"},
            {"Professional Studies Homeland Security", "PSHS"},
            {"Professional Studies Integrated Information, Science, and Technology", "PSIS"},
            {"Professional Studies Landscape Design", "PSLD"},
            {"Professional Studies Law Firm Management", "PSLM"},
            {"Professional Studies Molecular Biology", "PSMB"},
            {"Professional Studies Paralegal Studies", "PSLX"},
            {"Professional Studies Public Leadership", "PSPL"},
            {"Professional Studies Public Relations", "PSPR"},
            {"Professional Studies Publishing", "PSPB"},
            {"Professional Studies Urban Sustainability", "PSUS"},
            {"Professional Studies Security and Safety Leadership", "PSSL"},
            {"Professional Psychology", "PSYD"},
            {"Psychology", "PSYC"},
            {"Public Health", "PUBH"},
            {"Public Policy and Public Admin", "PPPA"},
            {"Regulatory Affairs", "RAFF"},
            {"Religion", "REL"},
            {"School of Engineering and Applied Science", "SEAS"},
            {"School of Media and Public Affairs", "SMPA"},
            {"Slavic Languages and Literature", "SLAV"},
            {"Sociology", "SOC"},
            {"Spanish", "SPAN"},
            {"Special Education", "SPED"},
            {"Speech and Hearing Science", "SPHR"},
            {"Statistics", "STAT"},
            {"Strategic Management and Public Policy", "SMPP"},
            {"Sustainability", "SUST"},
            {"Theatre and Dance", "TRDA"},
            {"Tourism Studies", "TSTD"},
            {"Turkish", "TURK"},
            {"University Writing", "UW"},
            {"Vietnamese", "VIET"},
            {"Women and Leadership Program", "WLP"},
            {"Women's, Gender, and Sexuality Studies", "WGSS"},
            {"Yiddish", "YDSH"},
    };
}
